# Welcome to Jekyll!
# ì›ë˜ í…Œë§ˆë¡œ ë³µê·€: remote_theme: "mmistakes/minimal-mistakes" ë¡œ ë³€ê²½

# Theme Settings
remote_theme: "LeNPaul/portfolio-jekyll-theme"

# Site Settings
locale: "ko-KR"
title: "PM AI LAB"
title_separator: "|"
subtitle: "Since 2024"
name: "K.Oliver Park"
description: "Sincerely, Research in AIğŸ§"
url: "https://CroinDA.github.io"
baseurl: ""

# Site Author
author:
  name: "Kwangjin Park"
  avatar: "/images/Croin_logo_final.png"
  bio: "AIí•˜ëŠ” PM, Croinì…ë‹ˆë‹¤ğŸ‘‹"
  location: "Seoul, South Korea"
  email: "plks1304@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:plks1304@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/CroinDA"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/croinda/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/research.ai.pm/"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@pang5953"

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
timezone: Asia/Seoul

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Google Analytics
google_analytics: "G-HW2Y43VG7Q"

# Disqus Comments
disqus:
  shortname: "CroinDA"

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      author_profile: true